- name: Wait for system to become reachable over WinRM
  wait_for_connection:
    timeout: 900

- debug:
    msg: "{{ hostname }} - {{ local_admin_password }} - {{ win_password }}"

- name: Join domain as server
  win_domain_membership:
    dns_root_domain: "{{ root_domain }}"
    hostname: "{{ hostname }}"
    domain_admin_user: "{{ win_domain_admin }}@{{ root_domain }}"
    domain_admin_password: "{{ win_password }}"
    #local_admin_password: "{{ local_admin_password }}"
    state: "domain"
  register: add_server_to_domain

- debug:
    msg: "{{ add_server_to_domain }}"

- name: reboot | Rebooting Server after adding server to domain
  win_reboot:
    connect_timeout: 15
    post_reboot_delay: 15
    reboot_timeout: 120
  when: add_server_to_domain.reboot_required