---
# TODO: pass in "attacklab" alone for the CA naming
- name: configure ADCS Certificate Enrollment Web Service via Install-AdcsEnrollmentWebService
  win_shell: Install-AdcsEnrollmentWebService -CAConfig "{{hostname}}.{{root_domain}}\{{domain_name}}-{{hostname}}-CA" -AuthenticationType Kerberos -ApplicationPoolIdentity -Force
  register: adcs_enrollment_web_service
  become: yes
  become_user: "{{ root_domain }}\\{{ win_domain_admin }}"
  become_method: runas

- name: debug configuring ADCS Certificate Enrollment Web Service
  debug:
    msg: "{{ adcs_enrollment_web_service }}"

- name: reboot | Post ADCS certificate enrollment web service (120 post reboot delay)
  win_reboot:
    connect_timeout: 15
    post_reboot_delay: 120
    reboot_timeout: 120

- name: Ensure CertSvc is running
  win_service:
    name: CertSvc
    state: started
  register: certsvc_running
  until: certsvc_running.state == "running"
  retries: 15
  delay: 10

- debug:
    msg: "{{ certsvc_running }}"

- name: Ensure AppReadiness is running
  win_service:
    name: AppReadiness
    state: started
  register: appreadiness_running
  until: appreadiness_running.state == "running"
  retries: 15
  delay: 10

- debug:
    msg: "{{ appreadiness_running }}"

#Current Error:
#{
#    "changed": true,
#    "cmd": "Install-AdcsEnrollmentWebService -ApplicationPoolIdentity -CAConfig 'win2019-ADCS.attacklab.local\\attackrange-WIN2019-ADCS-CA' -AuthenticationType Kerberos -Force",
#    "delta": "0:00:00.578188",
#    "end": "2021-08-24 12:29:14.950459",
#    "msg": "non-zero return code",
#    "rc": 1,
#    "start": "2021-08-24 12:29:14.372271",
#    "stderr": "Install-AdcsEnrollmentWebService : CCertificateEnrollmentServerSetup::SetProperty: The parameter \r\nis incorrect. 0x80070057 (WIN32: 87 ERROR_INVALID_PARAMETER)\r\nAt line:1 char:65\r\n+ ... ing $false; Install-AdcsEnrollmentWebService -ApplicationPoolIdentity ...\r\n+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : NotSpecified: (:) [Install-AdcsEnrollmentWebService], ArgumentExcep \r\n   tion\r\n    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.CertificateServices.Deployment.C \r\n   ommands.CES.InstallAdcsEnrollmentWebService",
#    "stderr_lines":
#    [
#        "Install-AdcsEnrollmentWebService : CCertificateEnrollmentServerSetup::SetProperty: The parameter ",
#        "is incorrect. 0x80070057 (WIN32: 87 ERROR_INVALID_PARAMETER)",
#        "At line:1 char:65",
#        "+ ... ing $false; Install-AdcsEnrollmentWebService -ApplicationPoolIdentity ...",
#        "+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
#        "    + CategoryInfo          : NotSpecified: (:) [Install-AdcsEnrollmentWebService], ArgumentExcep ",
#        "   tion",
#        "    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.CertificateServices.Deployment.C ",
#        "   ommands.CES.InstallAdcsEnrollmentWebService"
#    ],
#    "stdout": "",
#    "stdout_lines":
#    []
#}