---
- name: Ensure CertSvc is running
  win_service:
    name: CertSvc
    state: started
  register: certsvc_running
  until: certsvc_running.state == "running"
  retries: 15
  delay: 10

- debug:
    msg: "{{ certsvc_running }}"

# TODO: pass in "attacklab" alone for the CA naming
- name: configure ADCS CA Web Enrollment via Install-AdcsWebEnrollment
  win_shell: Install-AdcsWebEnrollment -CAConfig 'win2019-ADCS.{{ domain_name }}\attacklab-WIN2019-ADCS-CA' -Force
  register: adcs_web_enrollment
  changed_when: adcs_web_enrollment.rc == 0
  failed_when:
    - adcs_web_enrollment.rc != 0
    - '"The Certification Authority Web Enrollment role is already installed" not in (adcs_web_enrollment.stderr|regex_replace("\r\n", ""))'
  become: yes
  become_user: "{{ domain_name }}\\{{ win_domain_admin }}"
  become_method: runas
  #become_flags: logon_type=batch
  #ignore_errors: yes

- name: debug configuring ADCS Web Enrollment
  debug:
    msg: "{{ adcs_web_enrollment }}"

- name: reboot | Post ADCS web enrollment (300 post reboot delay)
  win_reboot:
    connect_timeout: 15
    post_reboot_delay: 300
    reboot_timeout: 120

- name: Ensure AppReadiness is running
  win_service:
    name: AppReadiness
    state: started
  register: appreadiness_running
  until: appreadiness_running.state == "running"
  retries: 15
  delay: 10

- debug:
    msg: "{{ appreadiness_running }}"