---
- name: configure ADCS Certificate Enrollment Web Service via Install-AdcsEnrollmentWebService
  win_shell: Install-AdcsEnrollmentWebService -CAConfig "{{hostname}}.{{root_domain}}\{{domain_name}}-{{hostname}}-CA" -AuthenticationType Kerberos -ApplicationPoolIdentity -Force
  register: adcs_enrollment_web_service
  become: yes
  become_user: "{{ root_domain }}\\{{ win_domain_admin }}"
  become_method: runas

- name: reboot | Post ADCS certificate enrollment web service (120 post reboot delay)
  win_reboot:
    connect_timeout: 15
    post_reboot_delay: 120
    reboot_timeout: 120