---
- name: configure ADCS CA Web Enrollment via Install-AdcsWebEnrollment
  win_shell: Install-AdcsWebEnrollment -Force
  register: adcs_web_enrollment
  changed_when: adcs_web_enrollment.rc == 0
  failed_when:
    - adcs_web_enrollment.rc != 0
    - '"The Certification Authority Web Enrollment role is already installed" not in (adcs_web_enrollment.stderr|regex_replace("\r\n", ""))'
  become: yes
  become_user: "{{ root_domain }}\\{{ win_domain_admin }}"
  become_method: runas
#  async: 120
#  poll: 5

- name: debug configuring ADCS Web Enrollment
  debug:
    msg: "{{ adcs_web_enrollment }}"

- name: reboot | Post ADCS web enrollment (120 post reboot delay)
  win_reboot:
    connect_timeout: 15
    post_reboot_delay: 300
    reboot_timeout: 120

- name: Ensure CertSvc is running
  win_service:
    name: CertSvc
    state: started
  register: certsvc_running
  until: certsvc_running.state == "running"
  retries: 15
  delay: 10

- debug:
    msg: "{{ certsvc_running }}"

- name: Ensure AppReadiness is running
  win_service:
    name: AppReadiness
    state: started
  register: appreadiness_running
  until: appreadiness_running.state == "running"
  retries: 15
  delay: 10

- debug:
    msg: "{{ appreadiness_running }}"

# We only really need KerberosAuthentication to test PetitPotam, but I threw some extra in to play with
- name: Add Default Certificate Templates from list via Add-CATemplate
  win_shell: Add-CATemplate -Name "{{ item }}" -Force
  loop:
    - KerberosAuthentication
    - User
    - DomainController
    - DomainControllerAuthentication
  become: yes
  become_user: "{{ root_domain }}\\{{ win_domain_admin }}"
  become_method: runas