---
- name: ensure the ADCS feature is installed
  win_feature:
    name: AD-Certificate
    include_management_tools: yes
    include_sub_features: yes # we specifically need Certificate Authority Web Enrollment and Certificate Enrollment Web Service installed
    state: present
  register: adcs_installation

- name: reboot | Post ADCS install (120 post reboot delay)
  win_reboot:
    connect_timeout: 15
    post_reboot_delay: 120
    reboot_timeout: 120

- name: configure AD CS certification authority via Install-ADCSCertificationAuthority
  # need -Force or we get the error "Install-AdcsCertificationAuthority : Windows PowerShell is in NonInteractive mode. Read and Prompt functionality is not available."
  win_shell: Install-AdcsCertificationAuthority -CAType EnterpriseRootCa -CryptoProviderName "ECDSA_P256#Microsoft Software Key Storage Provider" -KeyLength 256 -HashAlgorithmName SHA256 -Force
  register: adcs_certification_authority_config
  changed_when: adcs_certification_authority_config.rc == 0
  failed_when:
    - adcs_certification_authority_config.rc != 0
    - '"The Certification Authority is already installed" not in (adcs_certification_authority_config.stderr|regex_replace("\r\n", ""))'
  become: yes
  become_user: "{{ root_domain }}\\{{ win_domain_admin }}"
  # we use become_method: runas in a lot of places because we get the error "The powershell shell family is incompatible with the sudo become plugin" if we use become normally
  become_method: runas

- name: reboot | Post ADCS certification authority (120 post reboot delay)
  win_reboot:
    connect_timeout: 15
    post_reboot_delay: 120
    reboot_timeout: 120