- name: Wait for system to become reachable over WinRM
  wait_for_connection:
    timeout: 900

- name: Add ActiveDirectory
  win_psmodule:
    name: ActiveDirectory
    state: present

- name: Create domain user accounts
  win_domain_user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    firstname: "{{ item.firstname | default() }}"
    surname: "{{ item.surname | default () }}"
    upn: "{{ item.firstname }}.{{ item.surname }}@attackrange.local"
    groups: "{{ item.add_group | default('Domain Users') }}"
  loop:
  - name: Phoebe Chillax
    firstname: Phoebe
    surname: Chillax
    password: "summer2021!"
  - name: Randy Random
    firstname: Randy
    surname: Random
    password: "QJMaNJ26fg43dPTd"
  - name: Tynan Sylvester
    firstname: Tynan
    surname: Sylvester
    password: "RimworldIsTheBest2021!"
    add_group: "Domain Admins"
  - name: Unconstrained User
    firstname: Unconstrained
    surname: User
    password: "Iamunconstrained2021!"

- name: unconstrained user unconstrained delegation set
  win_shell: "Set-ADAccountControl -Identity 'Unconstrained User' -TrustedForDelegation $True"
  register: unconstrained_delegation_set

- debug:
    msg: "{{ unconstrained_delegation_set }}"