- name: Install tools to help security testing
  win_chocolatey:
    name: '{{ item }}'
    state: present
  loop:
      - sysinternals
      - procexp
      - procmon
      - processhacker
      #- wireshark
      #- nmap
      #- dotpeek
      - dnspy
      #- ilspy
      #- pestudio
      #- explorersuite
      - ghidra
      #- x64dbg.portable
      #- ida-free
      #- ollydbg
      #- cutter
      #- radare2
      #- confuser
  ignore_errors: true