- name: Install tools to help development
  win_chocolatey:
    name: '{{ item }}'
    state: present
  loop:
    - visualstudio2019community
    - netfx-4.7.1-devpack
    - git
    - python3
    - microsoft-windows-terminal
    #- notepadplusplus
    - sublimetext3
    #- putty
    #- filezilla
    #- postman
    #- fiddler
  ignore_errors: yes