---

- name: Change dns server to domain controller
  win_dns_client:
    adapter_names: "Ethernet 2"
    ipv4_addresses: "{{ windows_domain_controller_private_ip }}"
# ansible_interfaces.0.connection_name
-
- name: reboot | Rebooting after setting DNS server
  win_reboot:
    msg: "Reboot after setting DNS server"

#- pause:
#    minutes: 3
#  when: use_packer == "1"

#- name: Copy join domain script to host
#  win_copy:
#    src: "join_domain.ps1"
#    dest: 'C:\join_domain.ps1'

#- name: Run join domain
#  win_shell: "C:\\join_domain.ps1 attackrange.local Administrator@attackrange.local {{ win_password }}"
#  register: win_shell_output

# - debug:
#     var: win_shell_output

-  name: Join domain
   win_domain_membership:
     dns_domain_name: "attackrange.local"
     hostname: "{{ hostname }}"
     domain_admin_user: "Administrator@attackrange.local"
     domain_admin_password: "{{ win_password }}"
     state: "domain"
     register: domain_state

- name: reboot | Reboot after joining domain
  win_reboot:
    msg: "Rebooting after joining domain"
  when: domain_state.reboot_required
