---

- name: Change dns server to domain controller
  win_dns_client:
    adapter_names: "Ethernet 2"
    ipv4_addresses: "{{ windows_domain_controller_private_ip }}"
# ansible_interfaces.0.connection_name

- name: reboot | Rebooting after setting DNS server
  win_reboot:
    msg: "Reboot after setting DNS server"

- debug:
    var: "{{ hostname }}"

-  name: Join domain
   win_domain_membership:
     dns_domain_name: "attackrange.local"
     hostname: "{{ hostname }}"
     domain_admin_user: "Administrator@attackrange.local"
     domain_admin_password: "{{ win_password }}"
     state: "domain"
   register: domain_state

- name: reboot | Reboot after joining domain
  win_reboot:
    msg: "Rebooting after joining domain"
  when: domain_state.reboot_required
