# Can't use ansible module because of: https://github.com/ansible/ansible/issues/32478
- name: Allow ICMP
  win_shell: Set-NetFirewallRule -DisplayName "File and Printer Sharing (Echo Request - ICMPv4-In)" -enabled True
  changed_when: false